tests: fix ci published ver pass

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -30,9 +30,14 @@ jobs:
           fetch-depth: 0
       - uses: actions/setup-node@v1
       - run: yarn --frozen-lockfile
-      - run: yarn -s dripip preview-or-pr
+      - run: yarn -s dripip preview-or-pr > result.json
         env:
           NPM_TOKEN: ${{secrets.NPM_TOKEN}}
+      - name: Save publish result
+        uses: actions/upload-artifact@v1
+        with:
+          name: published
+          path: result.json
 
   smoke-test:
     needs: publish
@@ -41,6 +46,10 @@ jobs:
       matrix:
         node-version: [10.x, 12.x]
     steps:
+      - name: Load publish result
+        uses: actions/download-artifact@v1
+        with:
+          name: published
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
@@ -59,5 +68,11 @@ jobs:
         env:
           LOG_LEVEL: trace
         run: |
-          export E2E_NEXUS_VERSION=$(yarn -s dripip get-current-commit-version)
+          export E2E_NEXUS_VERSION=$(jq -r '.version' < published/result.json)
+
+          if [ $E2E_NEXUS_VERSION == '' ]; then {
+            echo "Failed to extract version"
+            exit 1
+          }
+
           yarn test:e2e
