tests: fix ci published ver job pass (#430)

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -29,10 +29,19 @@ jobs:
         with:
           fetch-depth: 0
       - uses: actions/setup-node@v1
-      - run: yarn --frozen-lockfile
-      - run: yarn -s dripip preview-or-pr
+      - name: Install deps
+        run: yarn --frozen-lockfile
+      - name: Make release
+        run: |
+          yarn -s dripip preview-or-pr --json > result.json
+          cat result.json | jq '.'
         env:
           NPM_TOKEN: ${{secrets.NPM_TOKEN}}
+      - name: Save publish result
+        uses: actions/upload-artifact@v1
+        with:
+          name: published
+          path: result.json
 
   smoke-test:
     needs: publish
@@ -42,8 +51,11 @@ jobs:
         node-version: [10.x, 12.x]
     steps:
       - uses: actions/checkout@v2
+      - name: Load publish result
+        uses: actions/download-artifact@v1
         with:
-          fetch-depth: 0
+          name: published
+      - run: cat published/result.json | jq -r '.version'
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
@@ -59,5 +71,9 @@ jobs:
         env:
           LOG_LEVEL: trace
         run: |
-          export E2E_NEXUS_VERSION=$(yarn -s dripip get-current-commit-version)
+          export E2E_NEXUS_VERSION=$(cat published/result.json | jq -r '.version')
+          if [ $E2E_NEXUS_VERSION == '' ]; then {
+            echo "Failed to extract version"
+            exit 1
+          }
           yarn test:e2e
